app_folder/auth.py
from flask import render_template, Blueprint, session, redirect, url_for, request, flash
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from app_folder.views import elements_for_navbar

from .models import User, Project, Pronostic, Product, Participation

from bson import ObjectId


auth = Blueprint("auth", __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    session.clear()
    count_projects = 0
    
    if current_user.is_authenticated:
        return render_template('Home page/home.html', user=current_user, count_projects=count_projects)
    else:
        if request.method == 'POST':
            email = request.form.get('email')
            password = request.form.get('password')
            
            user = User.objects(email=email).first()     
            
            if user :
                if check_password_hash(user.password, password):
                    project_id = request.args.get('project_id')
            
                    if project_id : 
                        project = Project.objects(id=project_id).first()
                        project_name = project.name
                        user_id = user.id
                        project.update(push__users=user_id)
                        flash(f'Projet {project_name} rejoint avec succès !', category='success')
                        login_user(user, remember=True)
                        
                        session['selected_project'] = {
                        'id': str(project.id),
                        'name': project.name
                        }
                        return redirect(url_for('views.pronostic', count_projects=count_projects))
                    
                    else:
                        login_user(user, remember=True)
                        return redirect(url_for('views.home_page'))
                else:
                    return render_template('Auth/login.html', error="Mauvais mot de passe !", count_projects=count_projects)
            
            else:
                return render_template('Auth/login.html', error="Cet email ne possède pas de compte", count_projects=count_projects)
        
    return render_template('Auth/login.html', count_projects=count_projects)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    session.clear()
    count_projects = 0
    project_id = request.args.get('project_id')
    
    if current_user.is_authenticated:
        if project_id : 
                project = Project.objects(id=project_id).first()
                project_users = project.users
                if current_user.id in project_users:
                    flash('Vous avez déjà rejoint ce projet', category='info')
                    return redirect(url_for('views.home_page'))
                else:
                    project_name = project.name
                    project.update(push__users=current_user.id)
                    flash(f'Vous avez rejoins "{project_name}"')
                    return redirect(url_for('views.home_page'))
                
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        over_18_checkbox = request.form.get('over_18')
        if over_18_checkbox == 'on':
            over_18 = True
        else:
            over_18 = False
        
        user = User.objects(email=email).first()
        
        if user:
            return render_template('Auth/register.html', error='Cet utilisateur existe déjà', count_projects=count_projects)
        
        if len(email) < 4:
            return render_template('Auth/register.html', error='Le nom d\'utilisateur doit contenir au moins 4 caractères', count_projects=count_projects)
        
        if len(password) < 4:
            return render_template('Auth/register.html', error='Le mot de passe doit contenir au moins 4 caractères', count_projects=count_projects)
        
        if password == confirm_password:
            hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
            new_user = User(username=username, email=email, password=hashed_password, over_18=over_18)              
                    
            new_user.save()
            
            # send_confirmation_email(new_user.email)
            # flash('Un email de confirmation a été envoyé. Veuillez vérifier votre boîte de réception.', category='info')
            
            
            
            if project_id : 
                project = Project.objects(id=project_id).first()
                project_name = project.name
                new_user_id = new_user.id
                project.update(push__users=new_user_id)
                flash(f'Compte créé ! Connectez-vous pour rejoindre "{project_name}"')
                return redirect(url_for('auth.login'))
                        
            flash(f'Compte créé avec succès !', category='success')
            return redirect(url_for('auth.login'))
        
        else:
            return render_template('Auth/register.html', error='Les mots de passe ne correspondent pas', count_projects=count_projects)
        
    return render_template('Auth/register.html', count_projects=count_projects)

@auth.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    user_id = current_user.id
    elements_for_base = elements_for_navbar(user_id)

    user = User.objects(id=user_id).first()

    
    if request.method == 'POST':
        new_password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        
        if len(new_password) < 4:
            return render_template('Auth/register.html', error='Le mot de passe doit contenir au moins 4 caractères')
        
        if new_password == confirm_password:
            hashed_password = generate_password_hash(new_password, method='pbkdf2:sha256')
            user.password = hashed_password
        
            user.save()
        
            flash(f"Mot de passe modifié avec succès !", category='success')
        return redirect(url_for('views.my_profil', **elements_for_base))
        
    return render_template('Auth/change_password.html', user=current_user, **elements_for_base)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Déconnecté avec succès !', category='success')
    return redirect(url_for('auth.login'))

@auth.route('/delete', methods=['POST'])
@login_required
def delete_account():
    user_obj = User.objects(id=current_user.id).first()
    user_id = user_obj.id
    

    #Je vais d'abord m'occuper du projet pour lequel le user est l'admin :
        #I - Je m'occupe de mettre à jour les listes de pronostic et de participation pour chaque user du projet à supprimer
            #1 - Listing des ID de tous les produits du projet à supprimer (ObjectID)
            #2 - Listing des ID de tous les pronostics du projet à supprimer (ObjectID)
            #3 - Listing des ID de tous les users du projet à supprimer (ObjectID)
            
            #4 - Listing des ID de toutes les participations pour chaque produits (STR)
            #5 - Listing des ID de tous les pronostics (STR)
            
            #6 - Liste de l'ensemble des participations du user (ObjectID)
            #7 - Liste de l'ensemble des pronostics du user (ObjectID)
            
            #8 - Si une participation du user(#6) est dans la liste des participations du projet(#4), je la retire de sa liste
            #9 - Si un pronostic du user(#7) est dans la liste des pronostics du projet(#5), je le retire de sa liste
            
            #10 - Je supprime le projet ce qui en cascade supprime 
                # - Les objets pronostics
                # - Les objets produits
                # - Les objets participations
            
        #II - Le user a pu participer à des projets. Je dois donc supprimer ses infos dans les projets (id de ses pronos) + La trace de ses participations dans les produits 
            #11 - Listing de tous les projets dans lesquels le user est présent
            #12 - Suppression de la présence du user dans la liste des users pour chaque projet
            #13 - Suppression de ses pronos dans les listes des projets
            #14 - Listing de toutes les participations du user
            #15 - La participation a été envoyée ou reçu. Je ne vais pas la supprimer mais plutôt l'attribuer à un profil "user_deleted"
            #16 - Si la participation est financie, je retire sa promesse du montant "already_paid" du produit
            #117 - Si Don ou Prêt, "already_paid" = 0 et "type" = € pour le produit
            
        #III - Suppression du user ce qui en cascade supprime
            # - Ses objets pronostics
            # - Ses objets participations

   
 #I --------------------------------------------------------------------------------------------------------------------
    project_to_delete = Project.objects(admin=user_id).first()
    if project_to_delete is None:
        pass
    else:
        product_list = project_to_delete.product #1
        pronostic_list = project_to_delete.pronostic #2
        user_list = project_to_delete.users #3
        
        participations_list_str = []
        pronostics_list_str = []
        
        if product_list is None:
            pass
        else :
            for product_id in product_list: #4
                product = Product.objects(id=product_id).first()
                participations = product.participation
                for participation in participations:
                    participations_list_str.append(str(participation))

        if pronostic_list is None:
            pass
        else:

app_folder/templates/My profil/change_email.html
{% extends 'base.html' %}

{% block title %}
    Change username
{% endblock %}


{% block content %}
    <div>
        <!-- Mise en place d'une flèche pour revenir à liste_naissance.html -->
        <a href="{{ url_for('views.my_profil') }}">
            <img src="{{ url_for('static', filename='images/left-arrow.png') }}" alt="Logo" style="max-width: 50px; margin: 0 0 0 10px;">
        </a>
    </div>

    <div class="my_container">
        <div class="my_card inert_card">
            <h1>Changer d'email</h1>
            <form method="post">
                <label for="email">Adresse mail</label>
                <input type="email" class="form-control text-center" name="new_email" value="{{user_email}}" required>                
                <button type="submit" class="my_btn">Changer</button>
            </form>
            {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app_folder/templates/My profil/change_username.html
{% extends 'base.html' %}

{% block title %}
    Change username
{% endblock %}


{% block content %}

    <div>
        <!-- Mise en place d'une flèche pour revenir à liste_naissance.html -->
        <a href="{{ url_for('views.my_profil') }}">
            <img src="{{ url_for('static', filename='images/left-arrow.png') }}" alt="Logo" style="max-width: 50px; margin: 0 0 0 10px;">
        </a>
    </div>

    <div class="my_container">
        <div class="my_card inert_card">
            <h1>Changer de nom d'utilisateur</h1>
            <form method="post">
                <label for="username">Nom</label>
                <input type="username" class="form-control text-center" name="new_username" value="{{user_username}}" maxlength="20" required>                
                <button type="submit" class="my_btn">Changer</button>
            </form>
            {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app_folder/templates/My profil/my_profil.html
{% extends 'base.html' %}

{% block title %}
    Mon profil
{% endblock %}


{% block content %}

    <div class="my_container">
        <h1>Mon Profil</h1>
        <div class="multiple_btn_container">
            <a href="/change_username" class="my_btn">Changer le nom d'utilisateur</a>
            <a href="/change_email" class="my_btn">Changer l'adresse mail</a>
            <a href="/change_password" class="my_btn">Changer le mot de passe</a>
        </div>        
    </div>
    <div class="my_container">
        <form action="{{ url_for('views.change_notification') }}" method="POST">
            <div class="form_check form-switch">
                <input class="form_check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" name="notification_enabled" {% if current_user.notification_enabled %}checked{% endif %}>
                <label class="form_check-label" for="flexSwitchCheckChecked">Notifications</label>
            </div>
            <button type="submit" class="my_btn">Sauvegarder</button>
        </form>
    </div>

    
<!-- Structure de la fenêtre modale pour supprimer son profil -->
<div class="my_container">
    <div id="myModal_delete_profil" class="modal" onclick="closeModal_delete_profil()">
        <div class="modal_content">
            <div class="exit_cross">
                <span class="close_icon" onclick="closeModal_delete_profil()">&times;</span>
            </div>
            <form method="POST" action="{{ url_for('auth.delete_account') }}" class="p-5 text-center">
                <p>ATTENTION cette action est irréversible !</p>
                <button type="submit" class="btn btn-danger">Supprimer mon profil</button>
            </form>
        </div>
    </div>
</div>

<div class="my_container">
    <h1>Supprimer mon profil</h1>
    <p>Si vous souhaitez supprimer votre profil, cliquez sur le bouton ci-dessous.</p>
    <button onclick="openModal_delete_profil()" class="my_btn red_admin_button">Supprimer le profil</button>
</div>



<script>
    function openModal_delete_profil() {
        document.getElementById('myModal_delete_profil').style.display = 'flex';
    }
    
    function closeModal_delete_profil() {
        document.getElementById('myModal_delete_profil').style.display = 'none';
    }
</script>


{% endblock %}